### ISSUE TITLE
parameters of LSTM layers

### ISSUE THREAD

**Issue by RyuuseiX** [tuur/PredRelTimelines#1]
![error](https://user-images.githubusercontent.com/56125130/176617242-43acbbe2-7b76-4e75-b9fb-9fea249b1919.png)
I got an issue with the parameters of LSTM layers.
This is the error I got

TypeError: lstm() received an invalid combination of arguments - got (Tensor, tuple, list, int, int, float, bool, bool, bool), but expected one of:
 * (Tensor data, Tensor batch_sizes, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional)

Could you please tell me which version to use in each library in requirement.txt? OR if you know what's wrong with it please tell me.

**Comment by tuur** [comment]
Hi RyuuseiX,

I just checked and found that the versions I used at the time are most likely the following:

torch==0.2.0.post3
torchvision==0.1.9
numpy==1.13.3
python-dateutil==2.6.1
nltk==3.2.5
plotly==2.1.0
beautifulsoup4==4.6.0
bs4==0.0.1
lxml==4.1.0

Hopefully this works for you.

Kind regards,
Tuur

**Comment by RyuuseiX** [comment]
Hi Tuur,

It worked.
It's due to the torch version. I downgraded it to the lowest possible version, 0.4.1, and changed a few codes to make it work.

Thank you,
Ryuu
